Created       : Tue May 08 17:03:44 IST 2012
Last Modified : Mon May 14 20:20:32 IST 2012

* Introduction

  PRS is a simple Patient Record System to be used in clinics/medical centers,
  first written for the needs of the Charity Medical Center, Lajpat Bhavan,
  New Delhi. 

  PRS is released under the GNU Affero GPL v3. 

  It is designed to run from within a browser, but without an internet
  connection. Broad features will include:

  - Patient Contat information, visit and case history tracking
  - Doctor database and availability database
  - Invoice generation for paying patients.

* Dependencies

  Tornado v2.2.1 and SQLAlchemy 0.7.7 are included in their entirety. You will
  of course need Python 2.7 if you want to run on Unix or Mac. The Windows
  release bundles do away with this requirement as well.

* Some history

  Originally I wanted to implement this an offine HTML5 application using
  IndexedDB, which would be very simple to install and use. However the state
  of IndexedDB support is somewhat disappointing. Chrome suffers from numerous
  bugs, Firefox does not allow indexeddb creation for offline apps (file:///
  URIs). There is no IE release with support at all. It is all rather
  frustrating enough that I have decided to move it to a full web application
  served through tornado.

  The git tag corresponding to the point I abandoned the html5 approach is
  called 'indexeddb_noworkie'
